[package]
name = "fleetos-core"
version = "0.1.4"
edition = "2024"
license = "Apache-2.0"
authors = ["Philip Aster and the FleetOS Contributors"]
description = "Core primitives, identity, and protocol definitions for FleetOS"

[features]
default = ["minimal"]

# Base primitives required by almost everyone
minimal = ["dep:prost", "dep:tonic", "dep:tonic-prost", "dep:bytes", "dep:rand", "dep:chacha20poly1305", "dep:rustls", "dep:tracing", "dep:zeroize", "dep:x25519-dalek"]

# Attestation backends (All imply `minimal` so they have SpiffeId/Hash/Proto)
tpm = ["minimal", "dep:tss-esapi", "dep:sha2"]
apple-se = ["minimal", "dep:security-framework", "dep:sha2"]
vsock-attest = ["minimal", "dep:vsock", "dep:sha2"]

# CA signing helpers (fleetos-control only)
ca = ["minimal", "dep:rcgen", "dep:x509-cert", "dep:der"]

# Mock attestation. STRICTLY excluded from release builds via compile_error!
dev = ["minimal"]

# Meta-feature
full = ["tpm", "apple-se", "vsock-attest", "ca", "dev"]

# Meta-feature for everything except mock/dev attestation
production = ["tpm", "apple-se", "vsock-attest", "ca"]

# Future sharded/stateful-partition addressing model
experimental-ordinal-routing = []

bytes = ["dep:bytes"]
rcgen = ["dep:rcgen"]
x509-cert = ["dep:x509-cert"]
der = ["dep:der"]
tonic = ["dep:tonic"]
prost = ["dep:prost"]
tss-esapi = ["dep:tss-esapi"]
sha2 = ["dep:sha2"]

[dependencies]
async-trait = "0.1.92"
blake3 = { version = "1.8.6", default-features = false }
bytemuck = { version = "1.25.2", default-features = false, features = ["derive"] }
bytes = { version = "1.12.1", optional = true }
chacha20poly1305 = { version = "0.11.0", optional = true }
der = { version = "0.8.1", optional = true }
prost = { version = "0.14.4", optional = true }
rand = { version = "0.10.2", optional = true }
rcgen = { version = "0.14.9", optional = true }
rustls = { version = "0.23.43", optional = true }
security-framework = { version = "3.7.0", optional = true }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
sha2 = { version = "0.11.0", optional = true }
thiserror = { version = "2.0.20", default-features = false }
tonic = { version = "0.14.6", optional = true }
tonic-prost = { version = "0.14.6", optional = true }
tracing = { version = "0.1.44", optional = true }
tss-esapi = { version = "7.7.0", optional = true }
vsock = { version = "0.5.4", optional = true }
x25519-dalek = { version = "3.0.0", default-features = false, features = ["getrandom", "static_secrets"], optional = true }
x509-cert = { version = "0.3.0", default-features = false, features = ["builder"], optional = true }
zeroize = { version = "1.9.0", default-features = false, features = ["zeroize_derive"], optional = true }

[build-dependencies]
tonic-prost-build = "0.14.6"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fleetos_dev)'] }
